services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./ecommerce-be
    env_file: ./ecommerce-be/.env
    ports:
      - "8080:8080"
    volumes:
      - ./ecommerce-be:/app
      - /app/node_modules # Không để node_modules đè lên máy thật
      - uploads_data:/app/public/uploads
    command: npm run dev
    environment:
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - db

  frontend:
    build: ./dien-may-fe
    env_file: ./dien-may-fe/.env
    ports:
      - "5173:5173"
    volumes:
      - ./dien-may-fe:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true # Bật chế độ polling cho file watcher để hot-reload hoạt động trên Docker
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=3BDmORQaJ0YIGShRufFObcYRJzG_7igZ8KLDEpKGegkqGf9LJ
    command:
      - http
      - backend:8080 # 'backend' là tên service ở phía trên
      - --url=mildred-mucronate-overwarily.ngrok-free.dev
    depends_on:
      - backend

volumes:
  db_data:
  uploads_data: