services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./ecommerce-be
    env_file: ./ecommerce-be/.env
    ports:
      - "8080:8080"
    volumes:
      - ./ecommerce-be:/app
      - /app/node_modules # Không để node_modules đè lên máy thật
      - uploads_data:/app/public/uploads
    environment:
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - db

  frontend:
    build: ./dien-may-fe
    env_file: ./dien-may-fe/.env
    ports:
      - "5173:5173"
    volumes:
      - ./dien-may-fe:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
  uploads_data: